name: rhizu
description: "A new Flutter package project."
version: 0.1.0

environment:
  sdk: ^3.12.0-30.0.dev
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_svg: ^2.2.3
  google_fonts: ^8.0.0
  hugeicons: ^1.1.5
  path_drawing: ^1.0.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.1.0

flutter:
  assets:
    - assets/shapes/
